name: Project 4 Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Web folder mein jana
            cd /var/www/html
            
            # 1. Purani portfolio files ko backup ya delete karna (Safety ke liye)
            # Hum saari purani files delete kar rahe hain taaki sirf Royal Events dikhe
            sudo rm -rf *
            
            # 2. Git setup aur code pull karna
            sudo git config --global --add safe.directory /var/www/html
            
            # Agar .git folder nahi hai (jo ki hoga kyunki humne rm -rf kiya)
            # Toh fresh clone karenge
            sudo git clone https://github.com/suhel33/localrepo.git .
            
            # 3. Permissions fix karna
            sudo chown -R ubuntu:ubuntu /var/www/html
            
            # 4. Nginx restart karna
            sudo systemctl restart nginx
